<remote>:
    orientation: 'vertical'

    Label:
        text: " Télécommande ! "

    Button :
        text: "Up"
        on_press :
            print(" up ! ")

    Button :
        text: "Down"
        on_press :
            print(" Down ! ")

    Button :
        text: "Right"
        on_press :
            print(" Right ! ")

    Button :
        text: "Left"
        on_press :
            print(" Left ! ")